name: Build & Test & Upload Docker Image

on:
    push:
        branches: [ main ]

env:
    DOCKERHUB_IMAGE: zealyen0526/rover-gq-action:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Docker
        run: docker build . -f Dockerfile -t $DOCKERHUB_IMAGE
      - name: generate test file
        run: echo "fake confidential data" > foo.yml
      - name: Retrieve runner uid and gid
        id: uid-gid
        run: |
          echo "uid=$(id -u)" >> $GITHUB_OUTPUT
          echo "gid=$(id -g)" >> $GITHUB_OUTPUT
      - name: Test the action
        uses: ./
        env:
          UID: ${{ steps.uid-gid.outputs.uid }}
          GID: ${{ steps.uid-gid.outputs.gid }}
        with:
          apollo_key: ${{ secrets.APOLLO_KEY }}
          apollo_graph_ref: 'ionex-core-web-xot5x@test'
          schema_path: 'test.graphql'
    #   - name: Print encrypted string
    #     run: |
    #       id
    #       ls -al foo.yml
    #       cat foo.yml
    #   - name: Login to Docker Hub
    #     uses: docker/login-action@v2
    #     if: github.ref == 'refs/heads/main'
    #     with:
    #       username: ${{ vars.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}
    #   - name: Push Docker Image
    #     if: github.ref == 'refs/heads/main'
    #     run: docker push $DOCKERHUB_IMAGE